<a href="https://colab.research.google.com/github/Younhong/Tensorflow-Python-JS/blob/master/src/python/tensorflow_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import tensorflow as tf

In [ ]:
# 파일로부터 데이터 읽어오기
파일경로 = 'https://raw.githubusercontent.com/Younhong/Tensorflow-Python-JS/master/data/lemonade.csv'
레모네이드 = pd.read_csv(파일경로)
print(레모네이드.head())

   온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48


In [ ]:
# 독립변수와 종속변수 분리
독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]
print(독립.shape, 종속.shape)

(6, 1) (6, 1)


In [ ]:
# 모델을 만듭니다.
X = tf.keras.layers.Input(shape=[1])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [ ]:
# 모델을 학습시킵니다. 
model.fit(독립, 종속, epochs=1000, verbose=0)
# model.fit(독립, 종속, epochs=10)

In [ ]:
print(종속)

   판매량
0   40
1   42
2   44
3   46
4   48
5   50


In [ ]:
# 모델을 이용합니다. 
print(model.predict(독립))

[[-2.8109775]
 [-3.001807 ]
 [-3.1926363]
 [-3.383466 ]
 [-3.5742953]
 [-3.765125 ]]


In [ ]:
print(model.predict([[15]]))

[[-1.8568299]]


In [ ]:
파일경로 = 'https://raw.githubusercontent.com/Younhong/Tensorflow-Python-JS/master/data/boston.csv'
보스턴 = pd.read_csv(파일경로)
print(보스턴.columns)

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


In [ ]:
print(보스턴.head())

      crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]


In [ ]:
# 독립변수와 종속변수 분리
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [ ]:
# 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [ ]:
# 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
# model.fit(독립, 종속, epochs=10)

In [ ]:
print(model.predict(독립[5:10]))

[[25.585018]
 [20.42864 ]
 [17.337248]
 [ 8.71151 ]
 [16.991098]]


In [ ]:
print(종속[5:10])

   medv
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9


In [ ]:
# 모델의 수식 확인
print(model.get_weights())

[array([[-0.08613253],
       [ 0.07055643],
       [-0.05301312],
       [ 3.3287237 ],
       [ 1.936881  ],
       [ 4.0154448 ],
       [ 0.01605273],
       [-0.84282047],
       [ 0.14973554],
       [-0.01045402],
       [-0.01745798],
       [ 0.0149722 ],
       [-0.5793658 ]], dtype=float32), array([2.479514], dtype=float32)]


In [ ]:
파일경로 = 'https://raw.githubusercontent.com/Younhong/Tensorflow-Python-JS/master/data/iris.csv'
아이리스 = pd.read_csv(파일경로)
print(아이리스.head())

   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa


In [ ]:
# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)
print(아이리스.head())

   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0


In [ ]:
print(아이리스.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [ ]:
# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [ ]:
# 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [ ]:
# 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
# model.fit(독립, 종속, epochs=10)

In [ ]:
# 모델을 이용합니다
# 맨 처음 데이터 5개
print(model.predict(독립[:5]))

[[9.9938571e-01 6.1415689e-04 6.1342398e-08]
 [9.9755329e-01 2.4460482e-03 7.6007831e-07]
 [9.9878770e-01 1.2121026e-03 2.2338925e-07]
 [9.9626982e-01 3.7291201e-03 1.0177530e-06]
 [9.9947268e-01 5.2728940e-04 4.2244938e-08]]


In [ ]:
print(종속[:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [ ]:
# 맨 마지막 데이터 5개
print(model.predict(독립[-5:]))

[[4.7440349e-07 9.3306847e-02 9.0669262e-01]
 [7.7708899e-07 1.3503022e-01 8.6496902e-01]
 [1.8688992e-06 2.2537754e-01 7.7462059e-01]
 [6.7110835e-07 1.7372471e-01 8.2627463e-01]
 [4.3179475e-06 3.8177803e-01 6.1821765e-01]]


In [ ]:
print(종속[-5:])

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [ ]:
# weights & bias 출력
print(model.get_weights())

[array([[ 0.7881301 , -0.09883678, -0.14533317],
       [ 3.3477554 ,  0.9349127 , -1.3164327 ],
       [-4.047819  , -0.06602266,  0.7481554 ],
       [-4.021424  , -1.7995704 ,  1.6958059 ]], dtype=float32), array([ 1.8011374,  1.3560863, -1.5775331], dtype=float32)]


In [ ]:
# 종속변수, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [ ]:
# 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [ ]:
# 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)

In [ ]:
model.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# 모델을 이용합니다
print(model.predict(독립[:5]))
print(종속[:5])

[[29.700005]
 [21.60816 ]
 [29.337194]
 [34.569008]
 [32.108154]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [ ]:
# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [ ]:
# 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [ ]:
# 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)

In [ ]:
# 모델을 이용합니다
print(model.predict(독립[:5]))
print(종속[:5])

[[1.00000000e+00 1.91023020e-09 1.07320565e-19]
 [1.00000000e+00 1.60293432e-08 5.50407469e-18]
 [1.00000000e+00 7.39296979e-09 2.26531352e-18]
 [1.00000000e+00 3.66301371e-08 2.97415800e-17]
 [1.00000000e+00 1.69447589e-09 9.99056207e-20]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [3]:
# 파일 읽어오기
파일경로 = 'https://raw.githubusercontent.com/Younhong/Tensorflow-Python-JS/master/data/iris2.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종
0   5.1  3.5    1.4   0.2   0
1   4.9  3.0    1.4   0.2   0
2   4.7  3.2    1.3   0.2   0
3   4.6  3.1    1.5   0.2   0
4   5.0  3.6    1.4   0.2   0

In [4]:
# 칼럼의 데이터 타입 체크
print(아이리스.dtypes)

꽃잎길이     float64
꽃잎폭      float64
꽃받침길이    float64
꽃받침폭     float64
품종         int64
dtype: object


In [5]:
# 품종 타입을 범주형으로 바꾸어 준다. 
아이리스['품종'] = 아이리스['품종'].astype('category')
print(아이리스.dtypes)

꽃잎길이      float64
꽃잎폭       float64
꽃받침길이     float64
꽃받침폭      float64
품종       category
dtype: object


In [6]:
# 카테고리 타입의 변수만 원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_0  품종_1  품종_2
0   5.1  3.5    1.4   0.2     1     0     0
1   4.9  3.0    1.4   0.2     1     0     0
2   4.7  3.2    1.3   0.2     1     0     0
3   4.6  3.1    1.5   0.2     1     0     0
4   5.0  3.6    1.4   0.2     1     0     0

In [8]:
# NA값을 체크해 봅시다. 
아이리스.isna().sum()

꽃잎길이     0
꽃잎폭      1
꽃받침길이    0
꽃받침폭     0
품종       0
dtype: int64

In [9]:
아이리스.tail()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭 품종
145   6.7  3.0    5.2   2.3  2
146   6.3  2.5    5.0   1.9  2
147   6.5  3.0    5.2   2.0  2
148   6.2  3.4    5.4   2.3  2
149   5.9  NaN    5.1   1.8  2

In [10]:
# NA값에 꽃잎폭 평균값을 넣어주는 방법
mean = 아이리스['꽃잎폭'].mean()
print(mean)
아이리스['꽃잎폭'] = 아이리스['꽃잎폭'].fillna(mean)
아이리스.tail()

3.0543624161073835


꽃잎길이       꽃잎폭  꽃받침길이  꽃받침폭 품종
145   6.7  3.000000    5.2   2.3  2
146   6.3  2.500000    5.0   1.9  2
147   6.5  3.000000    5.2   2.0  2
148   6.2  3.400000    5.4   2.3  2
149   5.9  3.054362    5.1   1.8  2