<a href="https://colab.research.google.com/github/Younhong/Tensorflow-Python-JS/blob/master/src/python/tensorflow_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import tensorflow as tf

In [2]:
# 파일로부터 데이터 읽어오기
파일경로 = 'https://raw.githubusercontent.com/Younhong/Tensorflow-Python-JS/master/data/lemonade.csv'
레모네이드 = pd.read_csv(파일경로)
print(레모네이드.head())

   온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48


In [4]:
# 독립변수와 종속변수 분리
독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]
print(독립.shape, 종속.shape)

(6, 1) (6, 1)


In [7]:
# 모델을 만듭니다.
X = tf.keras.layers.Input(shape=[1])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [8]:
# 모델을 학습시킵니다. 
model.fit(독립, 종속, epochs=1000, verbose=0)
# model.fit(독립, 종속, epochs=10)

In [9]:
print(종속)

   판매량
0   40
1   42
2   44
3   46
4   48
5   50


In [10]:
# 모델을 이용합니다. 
print(model.predict(독립))

[[40.103195]
 [42.064827]
 [44.026455]
 [45.988083]
 [47.94971 ]
 [49.91134 ]]


In [11]:
print(model.predict([[15]]))

[[30.295057]]


In [12]:
파일경로 = 'https://raw.githubusercontent.com/Younhong/Tensorflow-Python-JS/master/data/boston.csv'
보스턴 = pd.read_csv(파일경로)
print(보스턴.columns)

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


In [13]:
print(보스턴.head())

      crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]


In [14]:
# 독립변수와 종속변수 분리
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [15]:
# 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [16]:
# 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
# model.fit(독립, 종속, epochs=10)

In [17]:
print(model.predict(독립[5:10]))

[[27.159761]
 [22.126957]
 [19.043999]
 [10.350985]
 [18.718842]]


In [18]:
print(종속[5:10])

   medv
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9


In [19]:
# 모델의 수식 확인
print(model.get_weights())

[array([[-0.08333332],
       [ 0.07437811],
       [-0.0535443 ],
       [ 3.3254974 ],
       [ 2.5015566 ],
       [ 3.7885919 ],
       [ 0.02102655],
       [-0.80930483],
       [ 0.1491606 ],
       [-0.00840003],
       [ 0.02081569],
       [ 0.01733215],
       [-0.59696907]], dtype=float32), array([2.7518592], dtype=float32)]


In [20]:
파일경로 = 'https://raw.githubusercontent.com/Younhong/Tensorflow-Python-JS/master/data/iris.csv'
아이리스 = pd.read_csv(파일경로)
print(아이리스.head())

   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa


In [21]:
# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)
print(아이리스.head())

   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0


In [22]:
print(아이리스.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [23]:
# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [24]:
# 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [25]:
# 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
# model.fit(독립, 종속, epochs=10)

In [26]:
# 모델을 이용합니다
# 맨 처음 데이터 5개
print(model.predict(독립[:5]))

[[9.9925309e-01 7.4684730e-04 2.5275060e-08]
 [9.9618334e-01 3.8164307e-03 2.9629746e-07]
 [9.9859983e-01 1.4000080e-03 9.9578131e-08]
 [9.9686807e-01 3.1314848e-03 4.3195325e-07]
 [9.9948776e-01 5.1226525e-04 1.8342829e-08]]


In [27]:
print(종속[:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [28]:
# 맨 마지막 데이터 5개
print(model.predict(독립[-5:]))

[[4.2717491e-07 1.3921613e-01 8.6078340e-01]
 [1.0394981e-06 2.0989525e-01 7.9010373e-01]
 [2.4087337e-06 2.3022713e-01 7.6977050e-01]
 [5.9816830e-07 6.8662219e-02 9.3133718e-01]
 [7.4855275e-06 2.0777315e-01 7.9221934e-01]]


In [29]:
print(종속[-5:])

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [30]:
# weights & bias 출력
print(model.get_weights())

[array([[ 0.5247187 ,  0.8846938 , -0.7046297 ],
       [ 3.4494798 ,  0.03691679, -0.9880227 ],
       [-3.2239883 , -0.7164609 ,  1.288141  ],
       [-4.906492  , -1.05773   ,  2.0511148 ]], dtype=float32), array([ 2.101841 ,  0.7307457, -1.2984257], dtype=float32)]


In [31]:
# 종속변수, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [32]:
# 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [33]:
# 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)

In [34]:
model.summary()

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_4 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [35]:
# 모델을 이용합니다
print(model.predict(독립[:5]))
print(종속[:5])

[[27.322054]
 [21.349432]
 [27.170052]
 [29.47833 ]
 [29.94319 ]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [36]:
# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [37]:
# 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [38]:
# 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)

In [39]:
# 모델을 이용합니다
print(model.predict(독립[:5]))
print(종속[:5])

[[9.99999762e-01 8.83522595e-12 2.31729103e-07]
 [9.99996424e-01 1.41398526e-09 3.56389182e-06]
 [9.99999285e-01 8.07735961e-11 6.81147810e-07]
 [9.99999523e-01 4.02431456e-11 4.67842199e-07]
 [9.99999881e-01 2.28652145e-12 1.07174316e-07]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [40]:
# 파일 읽어오기
파일경로 = 'https://raw.githubusercontent.com/Younhong/Tensorflow-Python-JS/master/data/iris2.csv'
아이리스2 = pd.read_csv(파일경로)
아이리스2.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종
0   5.1  3.5    1.4   0.2   0
1   4.9  3.0    1.4   0.2   0
2   4.7  3.2    1.3   0.2   0
3   4.6  3.1    1.5   0.2   0
4   5.0  3.6    1.4   0.2   0

In [41]:
# 칼럼의 데이터 타입 체크
print(아이리스2.dtypes)

꽃잎길이     float64
꽃잎폭      float64
꽃받침길이    float64
꽃받침폭     float64
품종         int64
dtype: object


In [42]:
# 품종 타입을 범주형으로 바꾸어 준다. 
아이리스2['품종'] = 아이리스2['품종'].astype('category')
print(아이리스2.dtypes)

꽃잎길이      float64
꽃잎폭       float64
꽃받침길이     float64
꽃받침폭      float64
품종       category
dtype: object


In [43]:
# 카테고리 타입의 변수만 원핫인코딩
인코딩 = pd.get_dummies(아이리스2)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_0  품종_1  품종_2
0   5.1  3.5    1.4   0.2     1     0     0
1   4.9  3.0    1.4   0.2     1     0     0
2   4.7  3.2    1.3   0.2     1     0     0
3   4.6  3.1    1.5   0.2     1     0     0
4   5.0  3.6    1.4   0.2     1     0     0

In [44]:
# NA값을 체크해 봅시다. 
아이리스2.isna().sum()

꽃잎길이     0
꽃잎폭      1
꽃받침길이    0
꽃받침폭     0
품종       0
dtype: int64

In [45]:
아이리스2.tail()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭 품종
145   6.7  3.0    5.2   2.3  2
146   6.3  2.5    5.0   1.9  2
147   6.5  3.0    5.2   2.0  2
148   6.2  3.4    5.4   2.3  2
149   5.9  NaN    5.1   1.8  2

In [46]:
# NA값에 꽃잎폭 평균값을 넣어주는 방법
mean = 아이리스2['꽃잎폭'].mean()
print(mean)
아이리스2['꽃잎폭'] = 아이리스2['꽃잎폭'].fillna(mean)
아이리스2.tail()

3.0543624161073835


꽃잎길이       꽃잎폭  꽃받침길이  꽃받침폭 품종
145   6.7  3.000000    5.2   2.3  2
146   6.3  2.500000    5.0   1.9  2
147   6.5  3.000000    5.2   2.0  2
148   6.2  3.400000    5.4   2.3  2
149   5.9  3.054362    5.1   1.8  2

In [49]:
# 종속변수, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [51]:
# 모델의 구조를 BatchNormalization layer를 사용하여 만든다.
X = tf.keras.layers.Input(shape=[13])
 
H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
 
H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
 
H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
 
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [ ]:
# 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000)

In [53]:
# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [54]:
# 모델의 구조를 BatchNormalization layer를 사용하여 만든다.
X = tf.keras.layers.Input(shape=[4])
 
H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
 
H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
 
H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
 
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [ ]:
# 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000)